### ISSUE TITLE
無効なリンク

### ISSUE THREAD

**Issue by kosh04** [ntddk/ntddk.github.io#1]
about のページにて `https?://` がないためにリンクが正常に機能していない箇所があるようです。

- https://github.com/ntddk/ntddk.github.io/blob/master/about/index.html#L123
- https://github.com/ntddk/ntddk.github.io/blob/master/about/index.html#L132

**Comment by ntddk** [comment]
遅ればせながら，修正しました．
ありがとうございます～！
